[DatabaseLocal]
DB_PASSWORD = "12345"

[DatabaseSupabase]
DB_PASSWORD = "vljDCAfOANrdzhlp"
SUPABASE_DB_URL = "postgresql://postgres.sumzwqyscfjjaueluwyl:vljDCAfOANrdzhlp@aws-1-eu-north-1.pooler.supabase.com:5432/postgres"
SUPABASE_DB_PASSWORD = "vljDCAfOANrdzhlp"

[Odds]
ODDS_API_KEY = "99e3d9acf9msh496dbd8dd0fd05ap1f58d3jsnac43842e21b1"

[App]
PASSWORD = "Mowgli"